default: &default
  adapter: postgresql
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: chat_development

test:
  <<: *default
  database: chat_test

production:
  <<: *default
  database: chat_production