language: ruby
rvm:
    - 2.5

env:
    - AWS_USER_ID:"780722053658" AWS_ECR_API="780722053658.dkr.ecr.us-east-2.amazonaws.com/arquichat-repo"
services:
    - docker
    - postgresql
branches:
    only:
        - main
install:
    - docker-compose build

script:
    - docker-compose up -d
    - sed -i -e 's/\r$/\n/' start.sh
    - sed -i -e 's/\r$/\n/' stop.sh
    - sed -i -e 's/\r$/\n/' install.sh
    - zip -r latest *
    - mkdir -p dpl_cd_upload
    - mv latest.zip dpl_cd_upload/latest.zip

