language: ruby
rvm:
    - 2.5

env:
    - AWS_USER_ID:"780722053658" AWS_ECR_API="780722053658.dkr.ecr.us-east-2.amazonaws.com/arquichat-repo"
services:
    - docker
    - postgresql
branches:
    only:
        - main
install:
    - docker-compose build
    - docker-compose run --rm web rails db:create db:schema:load
