version: 0.0
os: linux

files:
  - source: .
    destination: /home/ubuntu/iic2173-proyecto-semestral-grupo9/scripts
permissions:
  - object: .
    pattern: "**"
    owner: ubuntu
hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 600
      runas: ubuntu
  AfterInstall:
    - location: install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: start.sh
      timeout: 600
      runas: ubuntu
