version: 0.0
os: linux

files:
  - source: scripts
    destination: /home/ubuntu
  - source: arquichat
    destination: /home/ubuntu/arquichat
permissions:
  - object: scripts
    pattern: "**"
    owner: root
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 600
      owner: root
  AfterInstall:
    - location: scripts/install.sh
      timeout: 600
      owner: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 600
      owner: root

