version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
#    env_file:
#      - ./.env_db
  web:
    build: .
    command: bundle exec rails s -p 8080 -b '0.0.0.0'
    restart: always
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
  #  env_file:
  #    - ./.env
    ports:
      - "8080:8080"
    depends_on:
      - db

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


  #www:
    #image: nginx
    #restart: always
    #expose:
    #  - "80"
    #volumes:
      #- /Users/kbs/git/peladonerd/varios/1/www:/usr/share/nginx/html:ro
    #  - .:/usr/src/app
    #environment:
    #  - VIRTUAL_HOST=201.214.87.63,www.201.214.87.63
    #  - LETSENCRYPT_HOST=201.214.87.63,www.201.214.87.63
    #  - LETSENCRYPT_EMAIL=pablo@201.214.87.63
    #depends_on:
    #  - web
volumes: 
  certs:
  html:
  vhostd:
